version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3099:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3099
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge 